version: 2

models:
  - name: customers
    description: "A simple customers model"
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - unique
          - not_null
  
  - name: first_customer
    description: "Table showing the name of the first customer"
    columns:
      - name: first_customer_name
        description: "Name of the first customer"

